# Patch: Add test-specific tags to AKSNodeClass
apiVersion: karpenter.azure.com/v1beta1
kind: AKSNodeClass
metadata:
  name: default
  namespace: kube-system
spec:
  tags:
    ManagedBy: karpenter
    Environment: test
    Cluster: test-uksouth
    Purpose: consolidation-testing
